### ISSUE TITLE
Support Node.js v20 or higher

### ISSUE THREAD

**Issue by dkastl** [hassio-addons/addon-base-nodejs#29]
# Problem/Motivation

I tried to install a module to Node-RED, which didn't work as it requires at least v20 of Node.js:

```
30 Oct 17:55:30 - [info] Installing module: @danpeig/node-red-meshtastic-msg, version: 1.4.3
30 Oct 17:55:36 - [warn] Installation of module @danpeig/node-red-meshtastic-msg failed:
30 Oct 17:55:36 - [warn] ------------------------------------------
30 Oct 17:55:36 - [warn] npm error code EBADENGINE
npm error engine Unsupported engine
npm error engine Not compatible with your version of node/npm: @danpeig/node-red-meshtastic-msg@1.4.3
npm error notsup Not compatible with your version of node/npm: @danpeig/node-red-meshtastic-msg@1.4.3
npm error notsup Required: {"node":">=20.x"}
npm error notsup Actual:   {"npm":"10.7.0","node":"v18.20.4"}
```

It seems that this base image repository specifies the Node.js version of the Node-RED addon, which is currently v18. 

I think support for v18 will soon end: https://nodejs.org/en/about/previous-releases
Is there a plan to upgrade the Node.js base image?

## Expected behavior

Support a newer version of Node.js, at least v20.

## Actual behavior

Base image uses Node.js v18.

## Steps to reproduce

Install `@danpeig/node-red-meshtastic-msg` in Node-RED addon.

**Comment by frenck** [comment]
The whole point for this repo to exists is tk have an older version…

Newer versions don’t play well with cross building Docker images on certain platforms (like armv7). This is a known issue that is caused by a change in NodeJS, triggering a bug in QEMU (which is used by Doxker buildx).

As long as that isn’t resolved upstream… I am blocked. Heck if it is fixed upstream, I can drop this base image fully!
